# Generated by Django 5.2.6 on 2026-03-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('model_3d', models.FileField(blank=True, help_text='Upload .glb or .gltf file for 3D viewer', null=True, upload_to='3d_models/')),
                ('material', models.CharField(choices=[('ceramic', 'Ceramic'), ('porcelain', 'Porcelain'), ('marble', 'Marble'), ('granite', 'Granite'), ('slate', 'Slate'), ('glass', 'Glass'), ('travertine', 'Travertine'), ('limestone', 'Limestone'), ('mosaic', 'Mosaic'), ('terracotta', 'Terracotta')], default='ceramic', max_length=50)),
                ('size', models.CharField(blank=True, help_text='e.g. "30x30cm", "60x60cm"', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
