# Generated by Django 5.2.6 on 2026-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_3d',
        ),
    ]
