# Generated by Django 4.2.11 on 2026-06-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_remove_product_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Other categories this tile should ALSO appear under (e.g. a floor tile also listed in Bathroom).', related_name='extra_products', to='core.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Primary category (shown as the main badge).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
