# Generated by Django 4.2.11 on 2026-06-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_additional_categories_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='Free text — type any size, e.g. "600x1200mm", "60x60cm", "2x2 ft"', max_length=50),
        ),
    ]
