# Generated by Django 5.2.17 on 2026-10-02 21:05

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, help_text="E.g. 'Floor and wall, indoor', 'Bathroom walls', 'Outdoor parking'.", max_length=200, verbose_name='where to use'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Manufacturer or brand of this tile.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=60, verbose_name='colour'),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, help_text='E.g. Matt, Glossy, Satin, Carving.', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='maintenance',
            field=models.TextField(blank=True, help_text='Cleaning and care advice.'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, verbose_name='SKU / product code'),
        ),
        migrations.AddField(
            model_name='product',
            name='slip_resistance',
            field=models.CharField(blank=True, help_text="Only if the manufacturer states it, e.g. 'R10' or 'Anti-skid'.", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, help_text='E.g. 9 mm.', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.gallery_image_path),
        ),
    ]
