/*
 * Tailwind build for the Suwasthik Tiles site.
 * Rebuild after changing template classes:  npm run build:css
 * The theme below is the design system that used to be inlined in base.html.
 */
module.exports = {
  content: ["./templates/**/*.html", "./static/js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdf90",
        "on-secondary": "#ffffff",
        "secondary": "#755b00",
        "tertiary-container": "#4f1a25",
        "surface": "#fff8f2",
        "outline": "#795e59", // was #8b716d (4.3:1); darkened for WCAG AA contrast
        "on-secondary-container": "#785d03",
        "primary-fixed": "#ffdad4",
        "surface-container-low": "#f9f2ec",
        "surface-container-highest": "#e8e1db",
        "inverse-on-surface": "#f6f0e9",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ca7e89",
        "on-surface-variant": "#58413e",
        "on-secondary-fixed-variant": "#584400",
        "on-tertiary": "#ffffff",
        "on-surface": "#1e1b17",
        "surface-dim": "#dfd9d2",
        "on-error-container": "#93000a",
        "surface-bright": "#fff8f2",
        "primary-container": "#610000",
        "primary": "#3a0000",
        "surface-container": "#f4ede6",
        "background": "#fff8f2",
        "inverse-surface": "#33302c",
        "on-tertiary-fixed": "#390915",
        "outline-variant": "#dfbfba",
        "surface-tint": "#a93729",
        "on-primary-fixed-variant": "#881f14",
        "surface-container-high": "#eee7e0",
        "secondary-container": "#fed979",
        "on-primary-container": "#ef6a58",
        "on-error": "#ffffff",
        "on-primary-fixed": "#410000",
        "inverse-primary": "#ffb4a8",
        "tertiary-fixed": "#ffd9dd",
        "tertiary": "#340511",
        "primary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed": "#241a00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#70343e",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#e6c366",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb2bc",
        "surface-variant": "#e8e1db",
        "on-background": "#1e1b17",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Montserrat", "sans-serif"],
        playfair: ["Playfair Display", "serif"],
        cormorant: ["Cormorant Garamond", "serif"],
        serif: ["Noto Serif", "serif"],
        display: ["Playfair Display", "serif"],
        literary: ["Cormorant Garamond", "serif"],
        "serif-alt": ["Cormorant Garamond", "serif"],
        "serif-display": ["Playfair Display", "serif"],
        "serif-light": ["Cormorant Garamond", "serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
