# Generated by Django 5.2.17 on 2026-10-02 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_prefill_business_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Page address: /policies/<slug>/', unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="The slug can't be only numbers. Add a word, e.g. 'floor-tiles'.", regex='^\\d+$')])),
                ('meta_description', models.CharField(blank=True, help_text='One or two sentences for search results (up to 160 characters).', max_length=160)),
                ('body', models.TextField(help_text='HTML. Use <h2> for headings, <p> for paragraphs, <ul><li> for lists, <a href> for links.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published pages are visible to customers and linked in the footer.')),
                ('show_in_footer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Page address: /guides/<slug>/', unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="The slug can't be only numbers. Add a word, e.g. 'floor-tiles'.", regex='^\\d+$')])),
                ('summary', models.TextField(help_text='A direct 1–3 sentence answer. Shown at the top of the guide and in search results.')),
                ('body', models.TextField(help_text='HTML. Use <h2> for headings, <p> for paragraphs, <ul><li> for lists, <a href> for links.')),
                ('cover_image', models.ImageField(blank=True, upload_to='guides/')),
                ('author_name', models.CharField(blank=True, help_text='Real name of the person who wrote or checked this guide (optional).', max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_category', models.ForeignKey(blank=True, help_text='Tiles from this category are suggested at the end of the guide.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
    ]
