# Generated by Django 5.2.17 on 2026-10-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0004_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address / location')),
                ('referrer_type', models.CharField(blank=True, choices=[('engineer', 'Civil Engineer'), ('mason', 'Mason'), ('layer', 'Layer (Tile Fixer)'), ('architect', 'Architect'), ('others', 'Others')], max_length=20, verbose_name='referred by')),
                ('referrer_name', models.CharField(blank=True, max_length=200, verbose_name="professional's name")),
                ('tile_interest', models.CharField(blank=True, max_length=255, verbose_name='tiles interested in')),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='area required (sq.ft)')),
                ('project_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('hospitality', 'Hospitality / Hotel'), ('restoration', 'Heritage Restoration'), ('outdoor', 'Outdoor / Landscaping')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote sent'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='The tile the customer was looking at when they asked for a quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name': 'quote request',
                'verbose_name_plural': 'quote requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
