# Generated by Django 5.2.17 on 2026-10-02 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text="E.g. 'Opp. Kalyana Mandabam, Bhavani, Erode Dt, Tamil Nadu'.", max_length=255, verbose_name='address (as shown on the site)')),
                ('street_address', models.CharField(blank=True, help_text="Street / landmark line for Google, e.g. 'Opp. Kalyana Mandabam'.", max_length=255)),
                ('locality', models.CharField(blank=True, max_length=100, verbose_name='town / city')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PIN code')),
                ('country', models.CharField(default='IN', help_text='Two-letter country code.', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('maps_url', models.URLField(blank=True, help_text="Used for the 'Get directions' button.", verbose_name='Google Maps link')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, help_text='With country code, digits only, e.g. 919876543210.', max_length=20, verbose_name='WhatsApp number')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, help_text="E.g. 'Mon–Sat, 9 AM to 7 PM'.", max_length=120, verbose_name='opening hours (as shown on the site)')),
                ('opening_hours_spec', models.CharField(blank=True, help_text="Schema.org format, e.g. 'Mo-Sa 09:00-19:00'. Several ranges: separate with commas.", max_length=120, verbose_name='opening hours for Google')),
                ('service_areas', models.CharField(blank=True, help_text='Towns/districts you deliver to, separated by commas.', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('google_business_url', models.URLField(blank=True, verbose_name='Google Business Profile link')),
                ('logo', models.ImageField(blank=True, upload_to='brand/')),
                ('share_image', models.ImageField(blank=True, help_text='1200×630 image used in link previews (WhatsApp, Facebook) when a page has no image of its own.', upload_to='brand/')),
                ('details_confirmed', models.BooleanField(default=False, help_text='Tick once the address, phone, email and hours above are correct. Only then are they published to Google (structured data) and the phone/email made clickable.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business info',
                'verbose_name_plural': 'business info',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short introduction shown at the top of the category page and used in search results.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Used in the page address: /products/<slug>/. Changing it changes the URL.', unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message="The slug can't be only numbers. Add a word, e.g. 'floor-tiles'.", regex='^\\d+$')]),
        ),
    ]
