"""
Download the site's web fonts from Google Fonts and self-host them.

    python scripts/update_fonts.py      (then: npm run build:css)

Writes static/fonts/*.woff2 and frontend/fonts.css (imported by
frontend/site.css). Run it again after adding a new Material Symbols icon to a
template (data-icon="..."), so the icon subset includes it. Self-hosting
removes two render-blocking requests to another domain and stops sending
visitors' IP addresses to Google.
"""
import hashlib
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "static" / "fonts"
CSS_OUT = ROOT / "frontend" / "fonts.css"
PRELOAD_OUT = ROOT / "templates" / "partials" / "font_preloads.html"
# Fonts needed above the fold on most pages: hero headings and header icons.
PRELOAD_PREFIXES = ("playfair-display-italic-latin-", "material-symbols-outlined-")
TEMPLATES = ROOT / "templates"

TEXT_FONTS = (
    "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;1,700"
    "&family=Noto+Serif:wght@400;700&family=Cormorant+Garamond:ital,wght@1,500;1,600"
    "&family=Inter:wght@400;500;600;700&family=Montserrat:wght@400;500;700&display=swap"
)
ICON_FONT = (
    "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1"
    "&icon_names={names}&display=block"
)
# Latin, plus Latin Extended (it contains the rupee sign ₹).
KEEP_SUBSETS = {"latin", "latin-ext"}
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0 Safari/537.36"
)


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read()


def used_icons():
    names = set()
    for path in TEMPLATES.rglob("*.html"):
        text = path.read_text(encoding="utf-8")
        names |= set(re.findall(r'data-icon="([a-z0-9_]+)"', text))
        names |= set(re.findall(r"dataset\.icon = [^;]*?'([a-z0-9_]+)'", text))
        for block in re.findall(r'data-icon="(\{%[^"]*)"', text):
            names |= set(re.findall(r"%\}([a-z0-9_]+)\{%", block))
    return sorted(names)


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def localise(css, label):
    """Keep wanted @font-face blocks, download their files, point src at /static/fonts/."""
    output = []
    for comment, block in re.findall(r"(?:/\* ([\w-]+) \*/\s*)?(@font-face\s*\{[^}]*\})", css):
        subset = comment or "all"
        if comment and comment not in KEEP_SUBSETS and comment != "fallback":
            continue
        url = re.search(r"url\(([^)]+)\)", block).group(1)
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        style = re.search(r"font-style:\s*(\w+)", block).group(1)
        digest = hashlib.sha1(url.encode()).hexdigest()[:8]
        filename = f"{slug(family)}-{style}-{subset}-{digest}.woff2"
        target = FONTS_DIR / filename
        if not target.exists():
            target.write_bytes(fetch(url))
            print(f"  downloaded {filename} ({target.stat().st_size // 1024} KB)")
        output.append(f"/* {label}: {family} {style} {subset} */\n" + block.replace(url, f'"../fonts/{filename}"'))
    return output


def main():
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    old_files = set(FONTS_DIR.glob("*.woff2"))

    text_css = fetch(TEXT_FONTS).decode("utf-8")
    icons = used_icons()
    icon_css = fetch(ICON_FONT.format(names=",".join(icons))).decode("utf-8")

    blocks = localise(text_css, "text") + localise(icon_css, "icons")
    icon_class = re.search(r"\.material-symbols-outlined\s*\{[^}]*\}", icon_css)
    if not icon_class:
        sys.exit("Unexpected icon CSS from Google Fonts (no .material-symbols-outlined rule).")

    header = (
        "/* Generated by scripts/update_fonts.py — do not edit by hand. */\n"
        f"/* Material Symbols subset ({len(icons)} icons): {','.join(icons)} */\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(blocks) + "\n\n" + icon_class.group(0) + "\n", encoding="utf-8")

    used = {Path(m) for m in re.findall(r'"\.\./fonts/([^"]+)"', CSS_OUT.read_text(encoding="utf-8"))}
    preload = sorted(u.name for u in used if u.name.startswith(PRELOAD_PREFIXES) and "latin-ext" not in u.name)
    lines = ["{# Generated by scripts/update_fonts.py: fonts used above the fold. #}{% load static %}"]
    for name in preload:
        lines.append(
            '<link rel="preload" href="{% static \'fonts/' + name + '\' %}" as="font" type="font/woff2" crossorigin/>'
        )
    PRELOAD_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    for stale in old_files:
        if stale.name not in {u.name for u in used}:
            stale.unlink()
            print(f"  removed unused {stale.name}")
    print(f"Wrote {CSS_OUT.relative_to(ROOT)} with {len(blocks)} @font-face rules; {len(icons)} icons.")


if __name__ == "__main__":
    main()
